kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo/yamls/bgd
    repoURL: https://github.com/redhat-apac-stp/gitops-practices.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
