apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: bgd
    namespace: openshift-gitops
  spec:
    destination:
      server: https://kubernetes.default.svc
    project: default
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: demo/yamls/bgd
      repoURL: https://github.com/redhat-apac-stp/gitops-practices.git
      targetRevision: main
kind: List
metadata:
  resourceVersion: ""
