# Proxy Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd-encryption
  namespace: openshift-gitops
spec:
  project: infra
  source:
    repoURL: https://github.com/redhat-apac-stp/gitops-practices.git
    targetRevision: main
    path: demo/kustomize/overlays/non-prod/etcd-encryption
  #syncPolicy:
    #automated: {}
      #selfHeal: true
      #prune: true
  destination: 
    name: in-cluster