# Proxy Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-proxy
  namespace: openshift-gitops
spec:
  project: infra
  source:
    repoURL: https://github.com/redhat-apac-stp/gitops-practices.git
    targetRevision: main
    path: demo/yamls/infra/cluster-proxy
  syncPolicy:
    automated: {}
      #selfHeal: true
      #prune: true
  destination: 
    name: in-cluster