kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocp-etcd-backup
  namespace: ocp-etcd-backup
  labels:
    app: ocp-etcd-backup
subjects:
  - kind: ServiceAccount
    name: ocp-etcd-backup
    namespace: ocp-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocp-etcd-backup